### ISSUE TITLE
Dependencies and Notebook

### ISSUE THREAD

**Issue by ColasRi** [giacomov/3ML#10]
Is 3ML supposed to be used mainly/only relying on notebook?
If not, maybe it would be good not necessarily require the notebook and its dependencies (eg zmq).
Eventually, 3ML installs properly but crashes at runtime:
```
[cr@crmac:~]$ ./extended.py 
Configuration read from /Users/cr/.threeML/threeML_config.yml
No module named zmq
```
Along these lines, can we display the formulas out of the notebook? Eventually just displaying the LaTeX code? From the current terminal output:
```
Spatial model: Point source
Formula:
<IPython.core.display.Latex object>
```

**Comment by giacomov** [comment]
3ML should not depend on the notebook by design, so this is a bug. 

The zmq dependency should not be there, I need to check what is causing that.

For the second problem we can change that as you suggest.

-----Original Message-----
