### ISSUE TITLE
get_errors() complaining when doing an error estimate

### ISSUE THREAD

**Issue by Vlasticak** [giacomov/3ML#101]
Hi,

I do the fit and then I want to get errors on my free parameters but when I run get_errors function it crashes with this message: 

CannotComputeErrors                       Traceback (most recent call last)
<ipython-input-39-0e812a6f9996> in <module>()
      8 jl2.fit()
      9 
---> 10 jl2.get_errors()

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/threeML-0.3.2-py2.7.egg/threeML/classicMLE/joint_likelihood.pyc in get_errors(self, quiet)
    314         assert self._current_minimum is not None, "You have to run the .fit method before calling errors."
    315 
--> 316         errors = self._minimizer.get_errors()
    317 
    318         # Set the parameters back to the best fit value

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/threeML-0.3.2-py2.7.egg/threeML/minimizer/minuit_minimizer.pyc in get_errors(self)
    350 
    351         if not self._migrad_has_converged():
--> 352             raise CannotComputeErrors("MIGRAD results not valid, cannot compute errors. Did you run the fit first ?")
    353 
    354         try:

CannotComputeErrors: MIGRAD results not valid, cannot compute errors. Did you run the fit first ?

**Comment by giacomov** [comment]
Hi,
this usually happens when there are one or more unconstrained parameters in the fit.

Can you post the entire output from your call to jl2.fit()?

**Comment by Vlasticak** [comment]
Here it is:

Best fit values:

#	Name	Best fit value	Unit
0	trigger.spectrum.main.composite.phoindex_3	1.185 +/- 0.011	
1	trigger.spectrum.main.composite.norm_3	0.946 +/- 0.006	keV / (cm2 s)
2	trigger.spectrum.main.composite.kt_4	1.10 +/- 0.08	keV
3	trigger.spectrum.main.composite.norm_4	0.0091 +/- 0.0018	keV / (cm2 s)

NOTE: errors on parameters are approximate. Use get_errors().


Correlation matrix:

1.00	0.05	0.88	0.91
0.05	1.00	0.16	-0.30
0.88	0.16	1.00	0.84
0.91	-0.30	0.84	1.00

Values of -log(likelihood) at the minimum:

-log(likelihood)
total	7075.536127
xrt	7075.536127

I also fitted this spectrum with Bayesian fitting and it gave the same result as ML but in ML it cannot compute errors.

**Comment by giacomov** [comment]
ok, so there doesn't seem to be anything wrong with the fit.

Can you attach the data files, so I can reproduce the problem and look into it?

**Comment by Vlasticak** [comment]
Here they are.

[Archive.zip](https://github.com/giacomov/3ML/files/564676/Archive.zip)

**Comment by giacomov** [comment]
@Vlasticak : I cannot reproduce your problem. This is what I did:

```python
from threeML import *
og = OGIPLike("test", "dio1.pha", "dio1_bkg.pha", "swxwt0to2s6_20110101v015.rmf","dio1.arf")
sp = Powerlaw() + Blackbody()
trigger = PointSource("trigger", 0.0, 0.0, sp)
model = Model(trigger)
data = DataList(og)
jl = JointLikelihood(model, data)
jl.fit()
```
with these results:

```
Best fit values:

 #                    Name                   Best fit value        Unit      
--- --------------------------------------- ---------------- ----------------
  0     trigger.spectrum.main.composite.K_1  0.422 +/- 0.006  1 / (cm2 keV s)
  1 trigger.spectrum.main.composite.index_1 -0.718 +/- 0.009                 
  2     trigger.spectrum.main.composite.K_2    1.04 +/- 0.04 1 / (cm2 keV3 s)
  3    trigger.spectrum.main.composite.kT_2  0.655 +/- 0.007              keV

NOTE: errors on parameters are approximate. Use get_errors().


Correlation matrix:

 1.00 -0.86 -0.71  0.39
-0.86  1.00  0.83 -0.67
-0.71  0.83  1.00 -0.90
 0.39 -0.67 -0.90  1.00

Values of -log(likelihood) at the minimum:

       -log(likelihood)
total       6962.883343
test        6962.883343
```

Then I tried to compute the errors, and it worked:

```python
jl.get_errors()
```
```
                                      Name                      Value  \
0      trigger.spectrum.main.composite.K_1        0.422 -0.006 +0.006   
1  trigger.spectrum.main.composite.index_1       -0.718 -0.009 +0.009   
2      trigger.spectrum.main.composite.K_2           1.04 -0.04 +0.04   
3     trigger.spectrum.main.composite.kT_2  0.65469 -0.00015 +0.00015   
```

I see from the log you posted earlier that your parameters are called differently, like trigger.spectrum.main.composite.phoindex_3 instead of mine  trigger.spectrum.main.composite.K_1. Did you have more than one source in your model?

**Comment by Vlasticak** [comment]
You are not using the same model as I am. It is XSPEC model and the models are: phabs*zphabs*pow and phabs*zphabs*(pow+zbb). I am traveling until Tuesday and don't have laptop with me and don't remember all parameters od phabs and zphabs I just remember that redshirt is 0.677.

**Comment by giacomov** [comment]
@Vlasticak When you have time can you give me the details of your model so I can reproduce the problem?

Thanks!

**Comment by Vlasticak** [comment]
Hi, 

sorry for not addressing this sooner.

`xspec_abund('angr')

spectral_model =  XS_phabs()* XS_zphabs() * XS_powerlaw()



spectral_model.nh_1=0.0148
spectral_model.nh_1.fix = True

spectral_model.nh_2=0.194134
spectral_model.nh_2.fix = True

spectral_model.redshift_2 = 0.677
spectral_model.redshift_2.fix =True



spectral_model2 =  XS_phabs()* XS_zphabs()*(XS_powerlaw()+XS_bbody())


spectral_model2.nh_1=0.0148
spectral_model2.nh_1.fix = True

spectral_model2.nh_2=0.194134
spectral_model2.nh_2.fix = True

spectral_model2.redshift_2 = 0.677
spectral_model2.redshift_2.fix =True
`

**Comment by giacomov** [comment]
I still cannot reproduce your error, but I am guessing a lot of things (the channels you use, the minimizer, and so on).

Can you please post a script that does everything you do (from importing threeML to the error), so that I can do exactly as you do from start to finish?

Thanks,

**Comment by Vlasticak** [comment]
%matplotlib notebook
import os
os.environ["MKL_NUM_THREADS"] = '1'
os.environ["NUMEXPR_NUM_THREADS"] = '1'
from threeML import *
xrt = OGIPLike('xrt',pha_file='dio1.pha')
xspec_abund('angr')

spectral_model =  XS_phabs()* XS_zphabs() * XS_powerlaw()



spectral_model.nh_1=0.0148
spectral_model.nh_1.fix = True

spectral_model.nh_2=0.194134
spectral_model.nh_2.fix = True

spectral_model.redshift_2 = 0.677
spectral_model.redshift_2.fix =True



spectral_model2 =  XS_phabs()* XS_zphabs()*(XS_powerlaw()+XS_bbody())


spectral_model2.nh_1=0.0148
spectral_model2.nh_1.fix = True

spectral_model2.nh_2=0.194134
spectral_model2.nh_2.fix = True

spectral_model2.redshift_2 = 0.677
spectral_model2.redshift_2.fix =True

ptsrc = PointSource('trigger',1,1,
                     spectral_shape=spectral_model)


model = Model(ptsrc)

data = DataList(xrt)

jl = JointLikelihood(model, data, verbose=False)


jl.fit()

data = DataList(xrt)

ptsrc2 = PointSource('trigger',1,1,spectral_shape=spectral_model2)
model2 = Model(ptsrc2)

jl2 = JointLikelihood(model2, data, verbose=False)

jl2.fit()

jl2.get_errors()

**Comment by grburgess** [comment]
@Vlasticak are you still having this issue?
