### ISSUE TITLE
Spectrum class common interface

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#142]
Since we will have a common spectrum class which has a common interface to FITS and ROOT files and should make no difference between seeing a file on disk and in memory, this mean we can easily go from ROOT -> FITS. This could be quite useful for XSPEC testing of ROOT data. 

I'm not sure if this functionality exists anywhere else in a general form. Should we make this a goal @giacomov ?

**Comment by giacomov** [comment]
I'm closing this as it is already solved.
