### ISSUE TITLE
SpectralModel.formula is dangerous

### ISSUE THREAD

**Issue by ColasRi** [giacomov/3ML#15]
It is the formula people see (well, if they use a notebook) but not what is used for computation.
That creates a risk of inconstancy. For instance,
`LogParabola.formula=r'\begin{equation}f(E) = A E^{\gamma+\beta \log(E)}\end{equation}'` does not correspond to the actual function: `return norm * (energies/piv)**(gamma+beta*numpy.log10(energies/piv))`

**Comment by giacomov** [comment]
Thanks for catching this.
In the new modeling package (astromodels) this should be easier to avoid than it is now.
