### ISSUE TITLE
Fit with a combination of models including Composite 

### ISSUE THREAD

**Issue by fryde** [giacomov/3ML#159]
Hi,
This bug is similar to my earlier issue: I am doing analysis with a Composite model and want to do a JointLikelihoodSet and GoodnessOfFit. This time I have added a model to the Composite model: e.g.  Composite + Powerlaw. I then get this error message:

UnknownFunction                           Traceback (most recent call last)
<ipython-input-301-50539061b314> in <module>()
      7 bgo0.fix_effective_area_correction(1.)
      8 
----> 9 g = GoodnessOfFit(jl_lundpl,res_lundpl[1])
     10 
     11 gof, data_frame, like_data_frame = g.by_mc(1000,continue_on_failure=False)

/usr/local/lib/python2.7/site-packages/threeML-0.3.2-py2.7.egg/threeML/classicMLE/goodness_of_fit.pyc in __init__(self, joint_likelihood_instance, like_data_frame)
     19 
     20         # Store best model
---> 21         self._best_fit_model = clone_model(self._jl_instance.likelihood_model)
     22 
     23     def get_simulated_data(self, id):

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in clone_model(model_instance)
     49     data = model_instance.to_dict_with_types()
     50 
---> 51     parser = ModelParser(model_dict=data)
     52 
     53     return parser.get_model()

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in __init__(self, model_file, model_dict)
     83             self._model_dict = model_dict
     84 
---> 85         self._parse()
     86 
     87     def _parse(self):

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in _parse(self)
    125             else:
    126 
--> 127                 this_parser = SourceParser(source_or_var_name, source_or_var_definition)
    128 
    129                 res = this_parser.get_source()

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in __init__(self, source_name, source_definition)
    262         if source_type == POINT_SOURCE:
    263 
--> 264             self._parsed_source = self._parse_point_source(source_definition)
    265 
    266         elif source_type == EXTENDED_SOURCE:

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in _parse_point_source(self, pts_source_definition)
    337 
    338         for component_name, component_definition in pts_source_definition['spectrum'].iteritems():
--> 339             this_component = self._parse_spectral_component(component_name, component_definition)
    340 
    341             components.append(this_component)

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in _parse_spectral_component(self, component_name, component_definition)
    418         shape_parser = ShapeParser(self._source_name)
    419 
--> 420         shape = shape_parser.parse(component_name, function_name, parameters_definition)
    421 
    422         # Get the links and extra setups, if any

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in parse(self, component_name, function_name, parameters_definition)
    481     def parse(self, component_name, function_name, parameters_definition):
    482 
--> 483         return self._parse_shape_definition(component_name, function_name, parameters_definition)
    484 
    485     @staticmethod

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/core/model_parser.pyc in _parse_shape_definition(self, component_name, function_name, parameters_definition)
    497 
    498             # This is a composite function
--> 499             function_instance = function.get_function(function_name, parameters_definition['expression'])
    500 
    501         else:

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/functions/function.pyc in get_function(function_name, composite_function_expression)
   1639         # Composite function
   1640 
-> 1641         return _parse_function_expression(composite_function_expression)
   1642 
   1643     else:

/usr/local/lib/python2.7/site-packages/astromodels-0.3.0-py2.7.egg/astromodels/functions/function.pyc in _parse_function_expression(function_specification)
   1775         else:
   1776 
-> 1777             raise UnknownFunction("Function %s in expression %s is unknown" % (unique_function, function_specification))
   1778 
   1779     # Check that we have found at least one instance.

UnknownFunction: Function lundman in expression (lundman{1} + Powerlaw{2}) is unknown

**Comment by giacomov** [comment]
This should be fixed now. Closing it.

**Comment by fryde** [comment]
Many thanks for this and a very nice analysis tool!

Felix



On 14 Feb 2017, at 20:09, Giacomo Vianello <notifications@github.com<mailto:notifications@github.com>> wrote:


This should be fixed now. Closing it.
