### ISSUE TITLE
Plugin to Support Binned Likelihood Profiles

### ISSUE THREAD

**Issue by woodmd** [giacomov/3ML#16]
It would be useful to have a plugin that would be able to ingest binned likelihood profiles and use them to evaluate the likelihood in lieu of running the analysis software of the respective experiment. 

Binned likelihood profiles are a way of encoding the likelihood function that preserves more information than a standard SED (i.e. flux points with 1 sigma errors).  The basic format would contain an NxM matrix of tabulated likelihood values as a function of N source flux values and M energy bins.  The [sed](http://fermipy.readthedocs.org/en/latest/advanced/sed.html) method in fermipy is an example of how this can be implemented in practice.

I'm planning to create a new page on [gamma-astro-data-formats](https://github.com/open-gamma-ray-astro/gamma-astro-data-formats) with a proposal for how we might serialize this information to a FITS file.  I'll post the link here when it's ready.

**Comment by woodmd** [comment]
I posted a first draft of a proposal for the [binned likelihood profiles FITS format](http://gamma-astro-data-formats.readthedocs.org/en/latest/results/binned_likelihoods/index.html).  In the next few weeks I'm planning to expand the page with more examples and use cases but I figured this would be a good reference point for further discussion.  Feedback/comments on the format would be welcome.

**Comment by grburgess** [comment]
@woodmd is this still needed?

**Comment by giacomov** [comment]
@grburgess I think we should implement this at some point. I was waiting for the format to become stable, and it looks like it did:

https://github.com/open-gamma-ray-astro/gamma-astro-data-formats/blob/03f465f83f977543efab2e0960ea33ddcbb616a4/source/spectra/binned_likelihoods/index.rst

**Comment by grburgess** [comment]
@woodmd @giacomov I've started a branch to begin work on this. I'm going to take a stab myself just learn this format. Just to be sure, it looks like the model embedded only gets scaled by a normalization, correct?

**Comment by woodmd** [comment]
I'm not sure what you mean.  What you are calculating for each energy bin is an array of normalizations (N_i) and an array of log-likelihood values (lnL_i).  To avoid a lot of unnecessary columns we've chosen to represent the amplitude of the bin as a dimensionless quantity `norm` which can be scaled with the appropriate `ref` column to translate it to flux, energy flux, or differential flux.

**Comment by giacomov** [comment]
This has been implemented in `CastroLike`. Closing issue.
