### ISSUE TITLE
analysis results and propagate

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#170]
I have noticed that propagate is having and issue with the XSPEC absorption models. 

I have a model that looks like this:

`spectral_model =  XS_phabs()* XS_zphabs() * XS_powerlaw()`

I do a fit and then try the model plot.

I plot have attached a plot that shows 4 things:

1) the plot directly from astromodels
2) the plot of the function I pass to propagate.
3) the propagated function where I have used the variates from the fit
4) the propagated function where I fix the arguments to their best fit values. 

I have added a small constant to make it easier to see:

![unknown-1](https://cloud.githubusercontent.com/assets/6764007/23895999/0a71b3d2-08a8-11e7-8535-7e261f54d03a.png)

The strange downward spikes are not correct. The direct function is, so the fit is working properly, it is simply the propagate function that is doing something very strange

**Comment by giacomov** [comment]
I'm trying to reproduce your problem.

Does this show up the same for different iterations of the same fit, or it is more random in nature?

Can you provide a minimal working example?

**Comment by grburgess** [comment]
It is general and not random. I will wrap up and example and attach in just a moment. Will you need some XRT data?

**Comment by giacomov** [comment]
maybe. In the meantime, what is the best fit value for Nh?

**Comment by grburgess** [comment]
Here is a full working example. the best fit is in question ;) 

but the problem is surely in propagate regardless of the fit values.

[test.zip](https://github.com/giacomov/3ML/files/842032/test.zip)

**Comment by grburgess** [comment]
And it is fixed. Thanks @giacomov !

![unknown-2](https://cloud.githubusercontent.com/assets/6764007/23923177/ef15f0d6-0905-11e7-99c6-9655d4375840.png)
