### ISSUE TITLE
reading of certain fits types failing.

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#187]
I found a bug in our fits reader that we need to correct. 

While the GBM CSPEC files claim to contain integer counts of type 128I -> signed short,
they are actually 128U -> unsigned short. This is fine and numpy dtype is mapped to:

```
_NUMPY_TO_FITS_CODE = {

    # Integers

    np.int16: 'I', # what the file claims we have in the header
    np.int32: 'J',
    np.int64: 'K',
    np.uint16: 'U', # what we have
    np.uint32: 'V',

    # Floating point

    np.float32: 'E',
    np.float64: 'D',

    }

```

however, astropy does not support this data type:

```
# mapping from TFORM data type to numpy data type (code)
# L: Logical (Boolean)
# B: Unsigned Byte
# I: 16-bit Integer
# J: 32-bit Integer
# K: 64-bit Integer
# E: Single-precision Floating Point
# D: Double-precision Floating Point
# C: Single-precision Complex
# M: Double-precision Complex
# A: Character
FITS2NUMPY = {'L': 'i1', 'B': 'u1', 'I': 'i2', 'J': 'i4', 'K': 'i8', 'E': 'f4',
              'D': 'f8', 'C': 'c8', 'M': 'c16', 'A': 'a'}

# the inverse dictionary of the above
NUMPY2FITS = {val: key for key, val in iteritems(FITS2NUMPY)}
# Normally booleans are represented as ints in pyfits, but if passed in a numpy
# boolean array, that should be supported
NUMPY2FITS['b1'] = 'L'
# Add unsigned types, which will be stored as signed ints with a TZERO card.
NUMPY2FITS['u2'] = 'I'
NUMPY2FITS['u4'] = 'J'
NUMPY2FITS['u8'] = 'K'
# Add half precision floating point numbers which will be up-converted to
# single precision.
NUMPY2FITS['f2'] = 'E'

# This is the order in which values are converted to FITS types
# Note that only double precision floating point/complex are supported
FORMATORDER = ['L', 'B', 'I', 'J', 'K', 'D', 'M', 'A']

# Convert single precision floating point/complex to double precision.
FITSUPCONVERTERS = {'E': 'D', 'C': 'M'}

# mapping from ASCII table TFORM data type to numpy data type
# A: Character
# I: Integer (32-bit)
# J: Integer (64-bit; non-standard)
# F: Float (64-bit; fixed decimal notation)
# E: Float (64-bit; exponential notation)
# D: Float (64-bit; exponential notation, always 64-bit by convention)
ASCII2NUMPY = {'A': 'a', 'I': 'i4', 'J': 'i8', 'F': 'f8', 'E': 'f8', 'D': 'f8'}

# Maps FITS ASCII column format codes to the appropriate Python string
# formatting codes for that type.
ASCII2STR = {'A': '', 'I': 'd', 'J': 'd', 'F': 'f', 'E': 'E', 'D': 'E'}

# For each ASCII table format code, provides a default width (and decimal
# precision) for when one isn't given explicitly in the column format
ASCII_DEFAULT_WIDTHS = {'A': (1, 0), 'I': (10, 0), 'J': (15, 0),
                        'E': (15, 7), 'F': (16, 7), 'D': (25, 17)}

```

So I suggest we remap the unreadable ints to a different format. I am not sure what type of effect this will have.

**Comment by giacomov** [comment]
I am not sure I understand. What has astropy to do with our reader? When does the problem arise in 3ML?

Regarding the 'U' format, it is supported by FITS:

https://heasarc.gsfc.nasa.gov/fitsio/c/c_user/node23.html

**Comment by grburgess** [comment]
It is supported by fits, but not by astropy. So when we try to use this line:

ln 211 in fits_file.py
```

                raise RuntimeError("Column %s in dataframe contains objects which are not strings" % column_name)

            this_column = fits.Column(name=column_name, format=format, unit=units, array=column_data)

            fits_columns.append(this_column)
```

it complains the the 'U' is not supported. I found that if I just use 'I' and 'J' for these data types, it works. 

Think we can just use that quick fix?

**Comment by giacomov** [comment]
It also looks like astropy does support unsigned integers:

http://docs.astropy.org/en/stable/io/fits/

by automatically reading them starting from >= 1.1.0. Before that version we would need to add a keyword to the .open() method.

Which version are you using?

**Comment by grburgess** [comment]
I am using '1.3.2'

looking at the source code I pasted above, I'm not sure where they are reading those types.

**Comment by giacomov** [comment]
One thing we can try is to construct the astropy.Table instance from the pandas, and then write that to file. That should take care of the unsigned int without us doing anything special.

I can look at this monday if you don't have time now.

**Comment by grburgess** [comment]
I always have time ;) 

I fixed it by doing this:

```
_NUMPY_TO_FITS_CODE = {

    # Integers

    np.int16: 'I', 
    np.int32: 'J',
    np.int64: 'K',
    np.uint16: 'I, # fake the type 
    np.uint32: 'J', # fake the type

    # Floating point

    np.float32: 'E',
    np.float64: 'D',

    }
```

I doubt this will affect anything as computers have big memory and integers can't change very much.

**Comment by giacomov** [comment]
Thanks! However, you need to make sure that you can write and read and back the file without the numbers changing (ideally this check should be in a test). If you cast an integer to an unsigned integer, it will change value in C/C++ (because the bits are interpreted differently).

**Comment by grburgess** [comment]
alright. I'll check it out.
