### ISSUE TITLE
Add README?

### ISSUE THREAD

**Issue by cdeil** [giacomov/3ML#2]
Can you please add a README file to the repo?

Markdown `.md` or RST `.rst` formats are common and nicely displayed by Github.

The info I'm looking for is how to get started, i.e. install `3ML` and run a first example.

**Comment by giacomov** [comment]
You are definitely right. However, we are working on documentation, tests and a pretty major re-factoring of the models part. A README and working examples will be coming in the upcoming weeks as soon as the re-factoring is completed and usable.
