### ISSUE TITLE
XS_gabs model is not correctly imported

### ISSUE THREAD

**Issue by volodymyrss** [giacomov/3ML#206]
I am not sure yet what is the cause, but the model takes only 0 or 1 values, no intermediate, independently of the strength. Position and width still work, but fit breaks, naturally, due to lack of sensitivity to strength.
cyclabs e.g. works well (but I don't need it now).

**Comment by grburgess** [comment]
@volodymyrss are you just needing to use a Gaussian? astromodels has that already (which could be much faster). 

But I do not see where gabs only takes 1 or 0

**Comment by giacomov** [comment]
I think I know what you mean. We had a similar problem in the past, but we thought we have solved it.

Make sure you have the latest version of threeML, and also clean up all the "XS_*.py" files in the directory ~/astromodels/data and try again.

The files in ~/astromodels/data are created the first time you import the xspec part of astromodels. It could be that you still have versions of those files created by a previous version of astromodels.

**Comment by volodymyrss** [comment]
I need in principle specific gaussian parameterization used in xspec, for consistency. Otherwise I have to keep converting parameters. Especially since it's gaussian absorption...

![image](https://cloud.githubusercontent.com/assets/3909535/26591977/a48f1dda-455f-11e7-9b45-a3765bff4aad.png)

**Comment by volodymyrss** [comment]
I run all inside docker, so the environment is, in principle, quite clean of any previous artifacts (ha! an advantage of ephemeral dockers).

I have just rebuild it with astromodels commit c86e4e0d (last one) and  get the same problem.

**Comment by volodymyrss** [comment]
I just have some concern with the fact that astromodels is installed twice: once by dependency of threeML from pip, and then from git once again.

**Comment by grburgess** [comment]
I do not think that will cause a problem (though I do not like that). I am taking a look right now

**Comment by grburgess** [comment]
I get the same problem. It is also strange that this is NOT a gaussian. I'll have a look at the XSPEC source code

**Comment by volodymyrss** [comment]
well it is (it is supposed to be) a gaussian absorption, and I see now that while function composition in astromodels is generally more advanced than in xspec, it does not allow to make an absorption of out if it... 

https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/node232.html
![image](https://cloud.githubusercontent.com/assets/3909535/26594833/91a47d0a-4569-11e7-9232-e231ec90ea31.png)

**Comment by grburgess** [comment]
@giacomov I think this is the same problem that we saw with the other absorption spectra (which I thought was fixed)

```cpp
// Converted from Fortran in xsgabs.f and modified to average exp(-tau) over
// the energy bin, not tau.
// number of model parameters:3
//       0       EL      line energy (in energy units, e.g. keV)
//       1       W       line width (sigma) (in energy units)
//       2       Tau     line optical depth
// intrinsic energy range: none
// algorithm:
//       M(E) = exp(-(tau/sqrt(2*PI)/W) * exp(-0.5*((E-EL)/W)**2)))
//       If W is less than or equal to zero, the line is treated as a delta
//            function.
//       N.B. when the energy spacing is much greater than W and the stepsize
//            for EL then the partial derivative determinations can lead
//            to fit error conditions.  The solution is to increase the
//            stepsize for EL


#include <XSFunctions/functionMap.h>
#include <xsTypes.h>
#include <XSstreams.h>
#include <cmath>
#include <XSUtil/Numerics/AdaptiveIntegrate.h>
#include <XSUtil/Numerics/BinarySearch.h>

using namespace Numerics;

RealArray gaussAbsIntegrand(const RealArray& x, void *p);

void gaussianAbsorptionLine(const RealArray& energyArray, const RealArray& params, 
			    int spectrumNumber, RealArray& fluxArray, 
			    RealArray& fluxErrArray, const string& initString)
{
  int nE = energyArray.size();
  fluxArray.resize(nE-1);
  fluxErrArray.resize(0);
  //fluxErrArray.resize(nE-1);
  fluxArray = 1.0;
  //fluxErrArray = 0.0;

  Real efirst = energyArray[0];
  Real elast = energyArray[nE-1];

  // Set the line energy, width and the energy range over which the
  // line will be calculated (essentially +/- crtsig sigma)

  Real crtsig = 6.0;
  Real emin = params[0] - crtsig*params[1];
  Real emax = params[0] + crtsig*params[1];

  // If the line calculation energies lie outside the energy range
  // then do not have to do anything

  if ( emax < efirst || emin > elast ) return;

  // find the first and last bins on which we need to calculate the absorption line

  int ifirst(0), ilast(nE-2);
  if ( emin >= efirst ) {
    ifirst = BinarySearch(energyArray, emin);
  }
  if ( emax <= elast ) {
    ilast = BinarySearch(energyArray, emax);
  }

  Real Precision = 1.0e-6;
  RealArray p(params);

  int ModelEvaluations(0);
  for (int i=ifirst; i<=ilast; i++) {

    Real Integral, IntegralError;
    ModelEvaluations += 
      AdaptiveIntegrate<gaussAbsIntegrand>(energyArray[i], energyArray[i+1],
					   &p, Precision, Integral, IntegralError);
    fluxArray[i] = Integral;
    //fluxErrArray[i] = IntegralError;
    Real ebin = energyArray[i+1]-energyArray[i];
    if ( ebin > 0.0 ) {
      fluxArray[i] /= ebin;
     // fluxErrArray[i] /= ebin;
    }


  }

  return;
}

// evaluate the gaussian absorption line integrand with p used to pass in the
// parameter values

RealArray gaussAbsIntegrand(const RealArray& x, void *p)
{
  RealArray OutArray(x.size());

  RealArray params(3);
  params = *(static_cast<RealArray*>(p));

  Real center = params[0];
  Real width  = params[1];
  Real tau    = params[2];

  Real gnorm = 1.0/width/sqrt(2*M_PI);

  for (size_t i=0; i<x.size(); i++) {
    Real gauss = gnorm * exp(-0.5*(x[i]-center)*(x[i]-center)/width/width);
    OutArray[i] = exp(-tau * gauss);
  }

  return OutArray;
}

```


It looks like they are looking for the width across the bins again... if I remember correctly. Thus, the problem exists in Sherpa too.

**Comment by giacomov** [comment]
Ok,
let me look into it. I'll get back to you here. 

@volodymyrss what do you mean by:

>  it does not allow to make an absorption of out if it

?

**Comment by volodymyrss** [comment]
>> it does not allow to make an absorption of out if it

> ?

i mean I can make some approximation of absorption like this (it's just first expansion term):

``
``

``python
1-Gaussian()
``

**Comment by grburgess** [comment]
It's most likely an error in the wrapper because XSPEC evaluates models at energy boundaries. We have run across this before with other absorption models.

**Comment by volodymyrss** [comment]
Note that `cyclabs` works just fine (or even phabs, for that matter).  Maybe it helps that not all absorption models are broken.

**Comment by giacomov** [comment]
@volodymyrss you can obtain what you want by using the .of() method, like:

```
# this is k*exp(-x/xc)
expo = Exponential_cutoff()
# fix xc=1
expo.xc = 1.0
expo.xc.fix = True
# Compose it with a Gaussian
line = Gaussian()
composition = expo.of(line)
```

The support for this is a little clunky, as we didn't really have a use case for it. It should work without issues in the fit, but if you want the units to work (which are needed for plotting, for example), you need at the moment to manually fix them:
```
# This will set the units in the functions
pts = PointSource("test", 0.0, 0.0, composition)
# We need to fix the Gaussian units so that Gaussian(x) / xc will have keV units
composition.F_2._unit = u.keV * u.keV
composition.functions[1]._y_unit = u.keV
# Now it works
print composition(1.0 * u.keV)
<Quantity 0.7850791607853478 1 / (cm2 keV s)>
```

**Comment by giacomov** [comment]
I fixed this in astromodels. 

The issue was that some of the multiplicative models require numerical differentiation because they compute the integral of the model over the energy bin. The "gabs" model is one of those.

**Comment by volodymyrss** [comment]
Yes, this works. Also the implementation is quite a bit faster than interface to xspec (though I have a feeling xspec alone was faster; I need to try more minimizers).
Thanks a lot!
