### ISSUE TITLE
"Current minimum stored after fit and current do not correspond!" messages with all PyGMO algorithms

### ISSUE THREAD

**Issue by volodymyrss** [giacomov/3ML#209]
I am getting "Current minimum stored after fit and current do not correspond!" messages with all PyGMO algorithms for a very simple model and data, which works with MINUIT.

**Comment by volodymyrss** [comment]
I was able to narrow it down a bit. I verified that `pagmo_minimizer.PAGMOMinimizer` itself works well on custom functions (e.g. `lambda x:(x-1)**2`), with various algorithms.

But if called through 3ml with something like `<bound method JointLikelihood.minus_log_like_profile of <threeML.classicMLE.joint_likelihood.JointLikelihood object at 0x7fc2c0b81190>>`, it never does any iterations: it always retuns the initial value. This appears as "converged" fit since the value does not change (it is <ftol).
The result is completely wrong though, of course.

**Comment by grburgess** [comment]
Yup. I am having this issue too. Also pyOpt appears to be broken

**Comment by grburgess** [comment]
I am now getting this via pyOpt and it seems connected to their distribution and not 3ML

```python
/Users/jburgess/.environs/3ml/lib/python2.7/site-packages/pyOpt/pyOpt_optimizer.pyc in __call__(self, opt_problem, *args, **kwargs)
    158 
    159         # Solve Optimization Problem
--> 160         return self.__solve__(opt_problem, *args, **kwargs)
    161 
    162 

/Users/jburgess/.environs/3ml/lib/python2.7/site-packages/pyOpt/pyMIDACO/pyMIDACO.pyc in __solve__(self, opt_problem, store_sol, disp_opts, store_hst, hot_start, *args, **kwargs)
    472                 liw0 = 2*nn + ll + 1000
    473                 liw = numpy.array([liw0], numpy.int)
--> 474                 iw = numpy.zeros([liw], numpy.int)
    475                 lrw0 = 200*nn + 2*mm + 1000
    476                 lrw = numpy.array([lrw0], numpy.int)

TypeError: only integer scalar arrays can be converted to a scalar index

```

**Comment by grburgess** [comment]
I fixed the issue with pyopt and emailed the developers. Development seems dead at the moment, so I just put it on git hub with my changes:

https://github.com/grburgess/pyOpt-1.2.0

**Comment by volodymyrss** [comment]
Between pagmo and pyopt not usable right now, I must say there is a bit of a crisis with good minimizers in 3ml, especially global. I also find ROOT often returns covariance full of NaN (#213).
For complex models with many lines it becomes a bit of an issue.

I am trying to do what I can, but I am not sure how to organize it best. Should I wait for functioning unit tests depending on third-party packages?

On the other hand, I can have a completely external package with minimizers and test it separately, only with required libraries, following the 3ml updates.  There are some disadvantages to this too, clearly.

I will try to add NLOpt too, I had very good experience with it.

**Comment by giacomov** [comment]
I did a complete rewriting of the minimization interface, fixing this issue and others.

Now there are two kinds of minimizers, Local (minuit, ROOT) and Global (Grid, pygmo). I didn't yet port pyopt nor Multinest (but will in the future).

The thing with pygmo was that they changed from version 1 to version 2 breaking compatibility, so I had to rewrite from scratch essentially.

I didn't have time yet to put together documentation, but this is an example about how to use various minimizers:

Local minimization:
```python
    minuit = LocalMinimization("minuit")
    minuit.setup(ftol=1e-3)  # This is optional
    
    jl.set_minimizer(minuit)
    fit_results, like_frame = jl.fit()
```

(note that the old way of saying jl.set_minimizer("minuit") still works, but gives you less control.

Global minimization:

A global minimizer always require also a second minimizer to improve the minimum found and to compute the errors. The second minimizer will also be used when doing contours and profiles (as it doesn't make sense to use the global one).

```python
    jl = JointLikelihood(...)

    pagmo = GlobalMinimization("PAGMO")
    minuit = LocalMinimization("minuit")

    algo = pygmo.algorithm(pygmo.bee_colony(gen=100))

    pagmo.setup(islands=4, population_size=20, evolution_cycles=1, second_minimization=minuit, algorithm=algo)

    jl.set_minimizer(pagmo)

    fit_results, like_frame = jl.fit()

```

or the new interface for Grid: 

```python
    jl = JointLikelihood(...)

    grid = GlobalMinimization("GRID")
    minuit = LocalMinimization("minuit")

    grid.setup(grid={jl.likelihood_model.bn090217206.spectrum.main.Powerlaw.K: np.linspace(0.1, 10, 10)},
               second_minimization=minuit)

    jl.set_minimizer(grid)

    fit_results, like_frame = jl.fit()

```

It is likely that there are going to be small issues with this change, but I think this is a good step in the right direction.

**Comment by giacomov** [comment]
I am writing you at 3 am before leaving for a week of vacation. When I came back I will write some decent documentation about this.

**Comment by grburgess** [comment]
Thanks! I'll check it out and fumble until you're back. I'm guessing we have scale parameters now?

**Comment by grburgess** [comment]
I realized that there were two version of pagmo and it is probably good to specify that this is the relevant link:

https://esa.github.io/pagmo2/install.html

**Comment by giacomov** [comment]
For completeness, this is the documentation:

http://threeml.readthedocs.io/en/latest/notebooks/Minimization_tutorial.html

**Comment by giacomov** [comment]
(please reopen if still relevant)

**Comment by volodymyrss** [comment]
Looks awesome! Thanks a lot!
