### ISSUE TITLE
"The fit failed to converge." messages do not leave useful information

### ISSUE THREAD

**Issue by volodymyrss** [giacomov/3ML#210]
It is pretty hard to trace the issue that lead to the "The fit failed to converge." message.
Is it possible to report the best parameters achieved, some additional information about the explored parameter range?

**Comment by volodymyrss** [comment]
I understand that it can be done for example with get_contours afterwards, but if exception raises somewhere deep the state of the objects may not allow that.
What I did for myself is replace these exceptions with warnings. It should be clearly recorded too in the state that the parameters are not the best fit.
I am not certain this is the best solution though.
What do you think?

**Comment by giacomov** [comment]
I added this. If the fit fails, the minimizer will try to print some useful information about the last iteration and the reason for failure.
