### ISSUE TITLE
ROOT minimizer returns covariance matrix with only NaNs

### ISSUE THREAD

**Issue by volodymyrss** [giacomov/3ML#213]
Sorry for this deliberately non-specific issue, but this is happening to me often in many situations.
I am wondering if you have seen this?

I can provide a unit test with example data, if travis tests support root.

**Comment by grburgess** [comment]
@volodymyrss This is normal if the fit is not working. I think people are far to familiar with LM optimization just spitting out numbers. The best way to make sure that the algorithm is working is with simulated data where the answer is known. Otherwise, if you can show an example where the fit is working with another software, this could really help narrow down the issue.

**Comment by volodymyrss** [comment]
Sometimes fit is not working and raises exception, sometimes it pretends to work and gives the values near-good, while the matrix is nan. There should be an exception or a more clear warning. Also there should be some way to explore parameter space to understand it if the fit does not work (see #210), I think.

I am ready to start populating the test kit with examples, in order to tune the optimization backend  3ml adopts has for different cases, to make sure they are functioning at least at the interface level.   

I do not really think people too familiar with fitting spitting out numbers. Not in my field anyway, where models are often complex and very complex. Fitting is a difficult problem, it depends on the exact situation.
Actually, I think the problem is often the opposite: people manually fine-tune the fitting so much that it is hard to tell  if the result is not biased by this process.
Ideally, I imagine, one should be able to use global optimizer to explore the whole allowed parameter range,  then perhaps local to fine-tune the minimum, and finally sample likelihood over the whole region to make sure you are actually estimating potentially disjoint confidence regions correctly.

I have a very specific case right now, one of the easiest line sources we have in fact. The problem that there is a lot of degeneracy and local minima. With xspec people manually drive it towards the minimum they like (from physical motivations and other instruments, different bands), and then estimate the errors locally, disregarding covariances. 

3ml has the potential to do it properly I think!

**Comment by giacomov** [comment]
Hi,
We have 3 possibilities for global minima searches in 3ML: the GRID minimizer, the GMO minimizer and the MULTINEST minimizer. 

The support for this is not rock solid as you have seen, they are at the experimental stage right now, but if you have a specific problem it might help us improve on that.

Please post somewhere an example and relative data files and I will be glad to work on this.

Sent from my Windows 10 phone

**Comment by volodymyrss** [comment]
Thank you for the effort! 
The specific issues with PAGMO are not data-specific, I would like to write a test to show it and verify later, but I do not think travis has PyGMO? Or it's ok with local-only tests?
I can of course just put files, if you are willing to help. but aren't unit tests more helpful, also to make sure that the future updates do not break the functionality?

**Comment by giacomov** [comment]
Yes, in general, but I’d rather see the problems and solve them interactively first, then once we are reasonably sure all issues have been solved we can make unit tests to make sure we will never regress.

Sent from my Windows 10 phone

**Comment by giacomov** [comment]
@volodymyrss following this and other issues you opened, I completely rewrote the minimization part to be more flexible and powerful. See this tutorial for some doc:

http://threeml.readthedocs.io/en/latest/notebooks/Minimization_tutorial.html

Let me know if you still have issues.

**Comment by volodymyrss** [comment]
I do confirm with pagmo I can get now a global fit in quite a complicated case (several broad absorption lines, entangled with multiple powerlaws), really very impressive, way beyond xspec experience! Thanks a lot!
On the other hand I still get correlation matrix of NaNs, with no warning even. I will explore more.
