### ISSUE TITLE
Adding lmfit to minimizers

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#217]
Shall we add this package:

https://lmfit.github.io/lmfit-py/

**Comment by giacomov** [comment]
Most of the algorithms are already in pygmo, so I am not sure about this.

Is there anything you would like to see?

**Comment by volodymyrss** [comment]
I pointed it out to @grburgess for a different reason really.
This packages combines interface to optimizers, samplers, some bayesian inference, structured model definition.
It can be seen an edge case of 3ml. 
Someone asked me how to fit some simple non-dispersion spectra, so I recommended 3ml. But then it was pointed out to me that lmfit can do it too, and it is much more lightweight.
Clearly, 3ml can do what lmfit does and much much more, but should it be recommended for this use case? 
This was my question.

**Comment by grburgess** [comment]
@giacomov I agree if this is a subset of what pagmo has, this it is good. But can we have other local minimizers besides ROOT or minuit? 

@volodymyrss I view this like other optimizers/samplers. In general, anyone could take this(or the other packages like minuit, emcee, etc) and perform a fit with data by building on top of them. We are offereing a unified multi-wavelength data interface with some bells and whistles on top. We also offer more options in terms of which optimizer/sampler you use and the framework is flexible enough that we can add on more. But all of this should be mosty transparent. So I view lmift as a fitting package and 3ML and a multi-wavelength data analysis framework. In the same way that I wouldn't compare ISIS, XSPEC etc to say multinest or D4nest even though they also provide a modeling framework (sort of).


I do not mind wrapping this. While ww may have some of the capabilites, it is nice for people to go to optimizers they know/trust and have the option. As long as it does not add overhead in maintainability for us. This pacakage seems stable. If anything, it allows for comparison and could turn out to be a better default than iminuit.

**Comment by giacomov** [comment]
Hi,
@grburgess pygmo offers many local optimizers thanks to the NLopt library. Look at the documentation for example.

Regarding lmfit, it seems to me that it is mostly for chisq fitting. Many algorithms there (like the Leven-Marquardt one) assume a least square problem, and even the computation of confidence interval assumes Gaussian statistic:

http://cars9.uchicago.edu/software/python/lmfit/confidence.html

I just had a quick look at the docs, I might be wrong though. If I am, then I would be open to introduce it as an alternative to the other local minimizers.

**Comment by volodymyrss** [comment]
absolutely, it's chi2 as far as I can see myself, so very narrow range of applications.
the question was more philosophical, should people use lmfit even when it formally applies? or use 3ml?

but there are some minimizers too, yes, but I did not look too deep.

**Comment by grburgess** [comment]
@giacomov I agree I think it is too narrow. But I can do this:
local_minimizer = LocalMinimization("pagmo")
... setup

correct?


@volodymyrss they could checkout the XYLike plugin. This would give them access to all minimizers etc. for simple data. Or the SpectrumLike plugin for binned data. Then, if later they need to do a joint fit with other types of data, it is rather easy to extend. But, it is preference.
