### ISSUE TITLE
Saving progress/ fits

### ISSUE THREAD

**Issue by drJfunk** [giacomov/3ML#23]
Dear all, 

I copy a conversation GV and I have been having here:

**Comment by drJfunk** [comment]
I’m working on a fit saving method. I think I have a really neat, novel idea, but it will take some time. I hope by the end of the week. If we can get this together… we can maybe make an announcement soon that it is ready for certain things

**Comment by drJfunk** [comment]
GV:

For saving fit results, can you explain the idea before implementing it, even if it's not fully formed? I am changing these days the format of the output of fitting and sampling routines to be more convenient when doing time-resolved fitting, and easier to save, so we should coordinate.

**Comment by drJfunk** [comment]
The basic idea is an base object that is inherited for bayesian or MLE fits. It stores parameters/marginals loglike/posteriors knows about models, selections etc. This way after a fit is made, the user passes the object to fit_save (or calls fit save on the object?) and the relevant information is in a new object.

Now, this object can write a fits/binary file that stores all this information as well as be able to read such files to restore it in python.

This makes the fitsave/fitinfo object the center.

For time-resolved, I was inspired by you linking of functions. I want to have it so you can link the fit objects to each other and they then know about each other in time. Then, they will have in iterator function or you can index them so that you can look over them in time for plotting. But all the time organization is done behind the scenes. Since they know about the models and parameters, you can do a loop and have the model change in time.

**Comment by drJfunk** [comment]
Hi,
I think this is a good thing to pursue. However, I don't think a custom format and a class is necessarily the way to go. I think we should divide things:

-saving the results of an analysis: a model from astromodels can already be saved and loaded from disk. Saving the samples or the likelihood profile is a very nice thing, but I would do it in a separate file. There are already discussions about a format for that on the github repository of the germans, but it's not finalized yet, so we can do other things until that's finalized. This way you could exchange a model which is the result of an analysis without having to send several MB of numbers (the samples or the profile). Also the output of model.save() is a YAML file which is easy to read and parse, with no binary data.

-saving a session: it means saving everything (all plugins, models, results). This is more for your own archive than to send around, because it will depend on your particular configuration (another user might not have the same plugins or data files). Since 3ML will be used also for proprietary data, some of these data cannot be exchanged. However, if we implement the first point, that plus the notebook itself would essentially provide the same functionality, right? I see it as a low-priority thing

-I am in the process of switching to using pandas for results. Pandas containers can be merged (for example, the results from different intervals can be appended in a big table by using .append()), easily plotted, saved and loaded from disk (http://pandas.pydata.org/pandas-docs/stable/io.html). They also provide out-of-the-box fancy displaying and many other features. So a time-resolved analysis would look like (pseudo-code):

# Define all the models you want to try with priors for the parameters

...

for i in range(n_intervals):

    # Load plugins for this interval

    ...

    data = DataList(...)

    for j, model in enumerate(models):

        jl = JointLikelihood(model, data)

        this_results = jl.fit()

        bs = BayesianAnalysis(model, data)

        this_samples = bs.sample(...)

        if j==0:

            results = this_results

            samples = samples

        else:

           results.append(this_results)

           samples.append(this_samples)

    if i==0:

        all_results = results

        all_samples = samples

    else:

        all_results.append(results)

        all_samples.append(samples)

plt.plot(all_results['alpha'])

all_results.to_hdf("time_resolved_results.hdf")

all_samles.to_hdf("samples.hdf")

We could place this code into a convenience function in the OGIP plugin so that if you have PHA2 files (as the GBM does) you can say all_results = time_resolved_analysis(...) and have it all in one line:

channels_lists = [["10.0-30.0", "40.0-10000.0"],"200-40000.0"]]

pha_list = ["nai0_pha.pha2","bgo0_pha.pha2"]

bak_list = [...]

rsp_list = [...] 

# Models you want to try

models = [model1, model2, ...]

all_results = time_resolved_analysis(pha_list, bak_list, rsp_list, channels_lists, models)

# Add priors to parameters

...

all_samples = time_resolved_bayesian_analysis(pha_list, bak_list, rsp_list, channel_lists, models)

Let's use as much as numpy, panda and scipy we possibly can, as those will continue to evolve and add amazing features. A specific file format should be avoided at all cost :-) It will also save us a ton of coding.

**Comment by drJfunk** [comment]
Ok: I agree this is better. So let's find a way to  keep the time resolved internal. 

Pandas is good. I've been using it for a while now as well and it is really built for this type of thing. 

If we go with pandas, I recommend using seaborn if we build plotting capability. Seaborn natively deals with pandas object.

**Comment by giacomov** [comment]
See #44
