### ISSUE TITLE
Python2 kernel in jupyter notebook dies while running the code

### ISSUE THREAD

**Issue by ShabnamIyyani** [giacomov/3ML#238]
After the installation of 3ML, before running it as instructed, in the terminal I initialised the softwares that I wanted to use like Fermi Science tools, Xspec (i.e heainit) etc and then activated the virtual environment for 3ML. Then within the environment I opened the Jupyter notebook  and tried running the basic example that was posted here at GItHub.  I get the following 
`%matplotlib inline
%matplotlib notebook

from threeML import *
WARNING NaimaNotAvailable: The naima package is not available. Models that depend on it will not be available

WARNING GSLNotAvailable: The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it will not be available.

WARNING XSpecNotAvailable: XSpec is not available.` 

The warnings were kind of odd as XSpec is working.  And after that Python2 kernel dies and shows that the Python has quitted unexpectedly. 

What could be the error? Is there anything wrong in the installation?

**Comment by grburgess** [comment]
The most likely cause for the kernel dying is a mismatch bewteen python libraries. You should investigate whether or not you have libraries installed in multiple python distributions. Python will load in order of its path these libraries and if it tries to access a binary that is incompatible with another, the kernel will die.
