### ISSUE TITLE
Problem when trying to Bayes sample

### ISSUE THREAD

**Issue by sptfung** [giacomov/3ML#24]
`samples = bayes.sample(n_walkers=50,burn_in=100, n_samples=1000)`

> Running burn-in of 100 samples...

emcee: Exception while calling your likelihood function:
  params: [   0.23218572   -0.40348434  196.39287035]
  args: []
  kwargs: {}
  exception:
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-x86_64/egg/emcee/ensemble.py", line 505, in __call__
    return self.f(x, *self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/threeML-0.2.0-py2.7.egg/threeML/bayesian/bayesian_analysis.py", line 569, in _get_posterior
    prior_value = parameter.prior(trial_values[i])
  File "build/bdist.macosx-10.10-x86_64/egg/astromodels/parameter.py", line 546, in _get_prior
    raise RuntimeError("There is no defined prior for parameter %s" % self.name)
RuntimeError: There is no defined prior for parameter K
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-fa2b7e756c50> in <module>()
----> 1 samples = bayes.sample(n_walkers=50,burn_in=100, n_samples=1000)

/usr/local/lib/python2.7/site-packages/threeML-0.2.0-py2.7.egg/threeML/bayesian/bayesian_analysis.pyc in sample(self, n_walkers, burn_in, n_samples)
    153         # Prepare the list of likelihood values
    154         self._log_like_values = []
--> 155         pos, prob, state = sampling_procedure(p0, sampler, burn_in)
    156 
    157         # Reset sampler

/usr/local/lib/python2.7/site-packages/threeML-0.2.0-py2.7.egg/threeML/bayesian/bayesian_analysis.pyc in sample_with_progress(p0, sampler, n_samples, **kwargs)
     35     progress_bar_iter = max(int(n_samples / 100),1)
     36 
---> 37     for i, result in enumerate(sampler.sample(p0, iterations=n_samples, **kwargs)):
     38         # Show progress
     39 

/usr/local/lib/python2.7/site-packages/emcee-2.1.0-py2.7.egg/emcee/ensemble.pyc in sample(self, p0, lnprob0, rstate0, blobs0, iterations, thin, storechain, mh_proposal)
    196         blobs = blobs0
    197         if lnprob is None:
--> 198             lnprob, blobs = self._get_lnprob(p)
    199 
    200         # Check to make sure that the probability function didn't return

/usr/local/lib/python2.7/site-packages/emcee-2.1.0-py2.7.egg/emcee/ensemble.pyc in _get_lnprob(self, pos)
    380 
    381         # Run the log-probability calculations (optionally in parallel).
--> 382         results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
    383 
    384         try:

/usr/local/lib/python2.7/site-packages/emcee-2.1.0-py2.7.egg/emcee/ensemble.pyc in __call__(self, x)
    503     def __call__(self, x):
    504         try:
--> 505             return self.f(x, *self.args, **self.kwargs)
    506         except:
    507             import traceback

/usr/local/lib/python2.7/site-packages/threeML-0.2.0-py2.7.egg/threeML/bayesian/bayesian_analysis.pyc in _get_posterior(self, trial_values)
    567         for i, (parameter_name, parameter) in enumerate(self._free_parameters.iteritems()):
    568 
--> 569             prior_value = parameter.prior(trial_values[i])
    570 
    571             if prior_value == 0:

/usr/local/lib/python2.7/site-packages/astromodels-0.1-py2.7.egg/astromodels/parameter.pyc in _get_prior(self)
    544 
    545         if self._prior is None:
--> 546             raise RuntimeError("There is no defined prior for parameter %s" % self.name)
    547 
    548         return self._prior

RuntimeError: There is no defined prior for parameter K

**Comment by giacomov** [comment]
Hi,
you need to define priors for all your parameters, they are required for the Bayesian analysis.

For example, if you have a power-law model, you can do it like this:
`
>>> my_powerlaw = Powerlaw()
>>> # define a log-uniform prior which is non-zero between 1e-7 and 1
>>> my_powerlaw.K.prior = Log_uniform_prior(lower_bound=1e-7, upper_bound=1)
>>> my_powerlaw.alpha.prior = Uniform_prior(lower_bound=-10, upper_bound=10)
`

You can also use the convenience function set_uninformative_prior of the Parameter class, which defines the prior using the current boundaries for the parameter (you need to have bounds defined):

`
# Mind that there are no () after the name of the prior because
# we are actually passing the class, not an instance
>>> my_powerlaw.K.set_uninformative_prior(Log_uniform_prior)
>>> my_powerlaw.alpha.set_uninformative_prior(Uniform_prior)
`

**Comment by sptfung** [comment]
Hi,

Sorry I should have mentioned that I have defined the priors for all my parameters, like this:

`cpl = Cutoff_powerlaw()`
`cpl.K.prior     = Log_uniform_prior(lower_bound=1E-2, upper_bound=5)`
`cpl.xc.prior    = Log_uniform_prior(lower_bound=1E2, upper_bound=2E3)`
`cpl.index.prior = Uniform_prior(lower_bound=-1.5,upper_bound=0.)`

**Comment by drJfunk** [comment]
Yes, 

I actually noticed something slightly different. 

Sometimes you have to define the priors twice to get the to stick. If you do not, then you will thrown and error:

`bayes = BayesianAnalysis(model, data_list)
band.K.prior     = Log_uniform_prior(lower_bound=1E-2, upper_bound=5)
band.xp.prior    = Log_uniform_prior(lower_bound=1E2, upper_bound=2E3)
band.alpha.prior = Uniform_prior(lower_bound=-1.5,upper_bound=0.)
band.beta.prior  = Uniform_prior(lower_bound=-3.,upper_bound=-1.5)

WARNING NonExistingAttribute: Attribute prior does not exist. Check for typos.
`

Executing the code twice fixes this issue. Somewhere the connection seems to be lost? Perhaps in astromodels?

**Comment by giacomov** [comment]
Thanks both for the reports. 

Please make sure you have the very latest versions from the repositories of both astromodels and 3ML.

Then, to understand where the problem is I need a minimal working example from both of you. Could you provide one?

**Comment by drJfunk** [comment]
I just updated astromodels and no change:


If you run the Fermi_TTE example, you should get the same problem.

Execute the data and model setup, and go to the bayesian section

**Comment by giacomov** [comment]
The problem has been corrected.

Also, now the BayesianAnalysis constructor enforce that all free parameters have priors defined.

I updated the Fermi_TTE example accordingly (BTW, that's awesome!)
