### ISSUE TITLE
Light curve plotting limit

### ISSUE THREAD

**Issue by sptfung** [giacomov/3ML#243]
Dear Giacomov,

In the Bayesian Blocks analysis example(http://threeml.readthedocs.io/en/latest/notebooks/Building_Plugins_from_TimeSeries.html?highlight=blocks), one can change the y-axiz limit by 

`_=plt.ylim(top=3000)`

however I get 

`NameError: name 'plt' is not defined`

I am wondering how could I change the y-axis limit using view_lightcurve?

Sincerely,
David

**Comment by giacomov** [comment]
Hi,
you just need to import matplotlib first:

```python
import matplotlib.pyplot as plt
```

**Comment by sptfung** [comment]
Dear Giacomo,

Thank you!

Best Regards,
David
