### ISSUE TITLE
Seaborn Plotting?

### ISSUE THREAD

**Issue by drJfunk** [giacomov/3ML#25]
Since we will be moving to Pandas for storing tables, etc., should we look at using seaborn for data descriptive plots? For example, seaborn can make the corner plots very nicely, and also allow the user to pass their preferred colormap.

**Comment by giacomov** [comment]
I like seaborn and I use it all the time, but at the same time is an experimental package from a Stanford PhD, don't know how long it will be supported, so I am hesitant to include in core functionalities.

I think one of the good things about seaborn is that you can import it before 3ML and it will automatically modify your plots.

Do you want to try that? If it doesn't work we might evaluate including it in setup.py .

**Comment by drJfunk** [comment]
Ah, yes, this always works. 

The feature I like is the native pandas handling. However, if you feel seaborn will fade away, then we can always deal with this ourselves.
