### ISSUE TITLE
ROI definitions in HAWCLike

### ISSUE THREAD

**Issue by rjlauer** [giacomov/3ML#258]
When creating a HAWCLike instance in order to use LiFF  in 3ML, the user has to provide a maptree-file, but is not automatically required to define a region-of-interest (ROI), i.e. a selection of pixels or coordinate range that will determine which part of the sky is being loaded internally in LiFF. Due to HAWC's large skymaps, the default so far is not to load the whole map, but rather to load an area chosen by a LiFF routine that tries to capture all sources defined in the model. This routine is far from perfect, in particular for extended morphologies, which is why the user has the option in 3ML to set the bool `fullsky` that will actually load the whole map.  
A confusing issue right now is that the 3ML `set_ROI` routines for defining an ROI manually are actually ignored if `fullsky` is False, i.e. LiFF will sttill automatically choose the ROI in that case.

Here is giacomov's detailed summary of these options (from a slack discussion):
"If `fullsky=True` -> the user *have* to call `set_ROI` (or one of the others `set_*_ROI` methods) after instancing the plugin. Then, when the `JointLikelihood` object is created, the `set_model` method of `HAWCLike` gets called. Within the method, the instance of the LiFF LikeHAWC class is created with all the data in memory and immediately after, the `setROI` method of LiFF is called and the ROI is defined. All unused data are discarded.
If `fullsky=False` -> the `set_ROI` method or the others `set_*_ROI` methods are useless, as the ROI is automagically chosen by LiFF. When the `JointLikelihood` object is created, the `set_model` method of `HAWCLike` gets called. Within the method, the instance of the LiFF LikeHAWC class is created and the ROI is automagically chosen by LiFF. Healpix pixels not within the ROI are never read from disk."

We are planning to change this behavior by allowing `set_ROI` to have effect even when  `fullsky=False`. LiFF will throw a fatal error if the user-chosen ROI is larger than what was loaded into memory (which happens before `set_ROI` is actually executed).

Also, we are debating to force the 3ML user to always manually set an ROI. This would likely break a number of scripts which rely on the automatic ROI choice, but it would expose this issue better. Comments are welcome.

**Comment by giacomov** [comment]
I am very much in favor of forcing the user to manually choose an ROI. However, in order to facilitate the transition, we can deprecate the automagic ROI choice first. That way the user who doesn't choose the ROI will get a warning, but not an error, so old script will keep working for a while.

@rjlauer what do you think?

**Comment by giacomov** [comment]
In the meantime I corrected the behavior mentioned above: now you can use one of the set_ROI methods even if fullsky=False. You will get a warning saying that it might fail, but it will work.
