### ISSUE TITLE
Counts spectrum shows data points for detectors beyond its energy selection criteria. 

### ISSUE THREAD

**Issue by ShabnamIyyani** [giacomov/3ML#259]
I had done the energy selections for NaI detectors  and BgO detectors using the following commands:                  
    NaI3.set_active_measurements( "10.0-30.0", "40.0-950.0" )
    NaI4.set_active_measurements( "10.0-30.0", "40.0-950.0" )
    NaI8.set_active_measurements( "10.0-30.0", "40.0-950.0" )
    Bgo0.set_active_measurements( "300.0-40000.0" ) 
However, after the fit when I plotted the counts spectrum with residuals I find NaI data at higher energies beyond its energy cut. 
I am attaching the plots of showing the energy selection of NaI 4 and Bgo0 detectors and also the counts spectrum after a fit. 
[Bgo0_energy_selection.pdf](https://github.com/giacomov/3ML/files/1470477/Bgo0_energy_selection.pdf)
[NaI4_energy_selection.pdf](https://github.com/giacomov/3ML/files/1470478/NaI4_energy_selection.pdf)
![counts_spec_band_023](https://user-images.githubusercontent.com/31057346/32776788-b7fd6a06-c959-11e7-9b33-69eeab86c377.png)

Here in the above counts spectrum, it is NaI 4 which is having a data point at 10^5 keV. In some other time bins of the analysis, other NaI detectors also show some data points greater than 1 MeV. 
But this is not happening in all the time resolved bins of the data which I am analysing. I am not sure why this is happening.

**Comment by giacomov** [comment]
@grburgess have you seen this?

**Comment by grburgess** [comment]
Yup. I'll grab it tomorrow

**Comment by grburgess** [comment]
@ShabnamIyyani would you mind attaching the data and code snippet that you used to produce these plots? It will help so that I can reproduce the problem.

**Comment by grburgess** [comment]
@giacomov it's the weighted average of the mean energies that is causing the bounds to go crazy. If the source rate is negative in a bin, the weights screw it up. I'm investigating

**Comment by grburgess** [comment]
@ShabnamIyyani It should be working now.
