### ISSUE TITLE
Exposure in FermiGBMLikeTTE

### ISSUE THREAD

**Issue by giacomov** [giacomov/3ML#26]
Need to implement the proper computation of exposure for Fermi/GBM.

Fermi/GBM has a deadtime for each recorded event. Look at the code in GtBurst, close to where you got the other code, for the function which computes that exposure.

**Comment by drJfunk** [comment]
Ah, ok, this is something I've been curious about. I will implement ASAP.

**Comment by drJfunk** [comment]
So GBM has 2E-6 s of dead time per event. =>

 exposure =  (tmax - tmin)  -    N_evt * 2E-6
where N_evt is the number of events in the interval between tmin and tmax

This is the closet that I can find in any documentation.

**Comment by giacomov** [comment]
Kind of, except that there is a larger deadtime for counts detected in the overflow channel.

This is a snippet of code which compute the deadtime for the GBM for one event, given its reconstructed channel PHA:

```
def get_deadtime(pha):

    #This return the deadtime associated with a given event
    #It is 2.6 microseconds if PHA!=127 and 10 microseconds if PHA==127 (overflow channel) 
    #(see Meegan et al. 2009)
    
   assert 1 <= pha <= 128, "Use channel numbers between 1 and 128"

    if pha==128:

      return 10E-6

    else:

      return 2E-6
```

**Comment by drJfunk** [comment]
Ok implemented in pull request of branch iss26
