### ISSUE TITLE
no FermiGBMLikeTTE?

### ISSUE THREAD

**Issue by sptfung** [giacomov/3ML#27]
Hi, 

I think the FermiGBMLikeTTE.py is not working?

I just reinstalled the new 3ML version today. When I type "Fermi" and hit tab, only FermiGBMLike comes up, no FermiGBMLikeTTE. Am I doing something wrong?

Thanks,
David

**Comment by giacomov** [comment]
It might be that you got a broken version of the package. I was working on a pretty substantial refactoring of all the GBM-related classes to avoid code duplication.

Try again, updating both 3ML and astromodels to the latest version, and tell me if it works.

thanks!
