### ISSUE TITLE
conda from master

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#275]
When does the master branch propagate to the conda install? Is it automatic or does it have to be pushed?

**Comment by giacomov** [comment]
It needs to be regenerated manually at the moment, but will soon be automatic. I am in the process of putting 3ML in conda-forge. I already created packages for all dependencies, even ROOT.

**Comment by giacomov** [comment]
The `conda build` is now automatic. Every time a build succeed in the master branch, a new release is updated to the `threeml` conda channel.
