### ISSUE TITLE
missing function make_index

### ISSUE THREAD

**Issue by giacomov** [giacomov/3ML#28]
The function make_index in the _hpd function in bayesian_analysis is undefined.

Also, since you are at hit @drJfunk , it is better to make the _hpd and _calc_min_interval as static methods of the BayesianClass. Just add the @staticmethod decorator before the definition, like:

```
    @staticmethod
    def _hpd(...)
        ....
```

and then of course you need to call them as self._hpd .

**Comment by drJfunk** [comment]
This is fixed for now. Need to address 2D distribution in the future. Reopen if needed.
