### ISSUE TITLE
Dropping ROOT for iminuit

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#283]
It seems iminiuit now uses minuit2:

https://github.com/iminuit/iminuit/pull/206

Shall we drop the ROOT support since it interferes so much with the parallel environment?

**Comment by giacomov** [comment]
The problem with the parallel environment has been solved, so we do not really have any reason to drop support. 

ROOT is an optional dependency right now, and iminuit is already the default minimizer, so I think we can skip this.
