### ISSUE TITLE
Non-convergence? 

### ISSUE THREAD

**Issue by drJfunk** [giacomov/3ML#29]
When running the example:
`jl = JointLikelihood( model, data_list, verbose=False )`
`res = jl.fit()`

If in the next cell I run:

`res = jl.get_errors()`

I get the following:

`CannotComputeErrors                       Traceback (most recent call last)`
`...`
`CannotComputeErrors: MIGRAD results not valid, cannot compute errors. Did you run the fit first ?`

I'm assuming that maybe it is not converging

**Comment by giacomov** [comment]
If that's the case, it should say so during the fit.

Do you have a working example?

MIGRAD is surprisingly not robust, and MINOS (used for error computation) even more so.

I want to implement a minimizer wrapping pyopt, which features global optimization techniques as well as newer and (hopefully) more robust minimizers.

**Comment by drJfunk** [comment]
Ah good, I was recommended that tool (pyopt) as well. It seems it is converging and as you say, it throws no error. But I have to execute the main fit twice to not throw this error. I will look to make and example. However, it is occurring running the demo.

**Comment by giacomov** [comment]
I just run the FermiGBM_TTE_Like Demo example and it worked without issues. That's weird.

I'm using the HEAD version of 3ML as of today, and iminuit version 1.1.1.

**Comment by drJfunk** [comment]
I have made a script demonstrating the problem (Run this in the examples folder.)
I am using iminuit 1.2. This could be the problem
The output I get:

`threeML.minimizer.minimization.CannotComputeErrors: MIGRAD results not valid, cannot compute errors. Did you run the fit first ?

![screenshot 2016-06-05 12 08 37](https://cloud.githubusercontent.com/assets/6764007/15804823/43eefbda-2b16-11e6-9722-89f0876e9c47.png)


[errors_bug.py.zip](https://github.com/giacomov/3ML/files/299282/errors_bug.py.zip)

`

**Comment by giacomov** [comment]
Fixed this. It seemed to be related to having the initial deltas too large. Try again with the GBM TTE demo.

**Comment by drJfunk** [comment]
Just a note. I was still having this issue until pyOpt. But it is now fixed
