### ISSUE TITLE
Priors and bounds

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#292]
I'm thinking about changing how the priors interact with the bounds set on parameters.

While it is important for full Bayes when we are just doing parameter estimation, we can forget about the data-dependent normalizing constants in the posterior. There are many times that I want to place an unbounded prior on a bounded parameter which will result in an assertion error. I want the soft behavior of these priors, but do not want to violate some physical bound.

Perhaps, it is better to just add -inf to the logposterior in these cases instead of throwing an error. This way we can set half-normal distributions, etc, without having to write tons  ofrenormalized functions.

**Comment by giacomov** [comment]
Can you provide an example?

Isn't it enough to make the parameter unbounded by setting min and Max to
None before making the computation?

**Comment by grburgess** [comment]
I'll provide an example soon. But that solution would not work. For example, if I have a physical parameter that cannot be less than 10, and I want to set a lognormal prior on it, I would need to write a  new function. This is of course possible, but it might become cumbersome. 

I'll play around and see if I can come up with a nice solution.

**Comment by giacomov** [comment]
Can't you just set a prior which is a log normal function multiplied by a
uniform prior with min value 10? Priors are just normal functions, they can
be multiplied, divided, added and so on.

**Comment by grburgess** [comment]
Aha, maybe that would work, but would the prior members are only present in some functions translate to the new composed function?

I'll check this out.

**Comment by giacomov** [comment]
Yeah, for multinest it won't work, because the unit cube thing won't
multiply... But for emcee style thing it should work
