### ISSUE TITLE
Adding PolyChord

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#33]
PolyChord is another nested sampling algorithm that hand handle multi-modal posteriors. It is an evolution over MULTINEST, but can be quite slow. It handles high dimensional parameter spaces very well because it uses slice sampling.

It is fairly easy to add on (they actually provide a python interface) and I've nearly completed this.
It will function in the same way as MULTINEST. However, they do not provide and analyzer. I will write a class in Bayesian analysis for this. 

Still, there are more advanced things you can do with the output. For now, I suggest we only extract the the simple stuff that we are doing for the other samplers and encourage the user to use other tools for posterior clustering analysis, etc. We could put these in in the future.

Thoughts?

**Comment by drJfunk** [comment]
PS: I have forked the PolyChord distro because it was only in CCForge and not easy to obtain. I added a kludge `make install` method as they do not provide one. 

Hopefully, they will work on this for themselves

**Comment by grburgess** [comment]
I'll take another stab at this now that they have their own python interface.
