### ISSUE TITLE
sources/models etc. wrt plotting

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#49]
I'm having a little trouble understanding the understanding the general idea multiple sources w.r.t. plotting.

Since a joint fit uses the same DataList for all sources, how does one handle the concept of multiple sources when considering point sources? I've assumed that all sources would have the same model type (not the same model instance) when summing, but I think this is a bad assumption. However, I really do not see what the point of having a source list with point sources at the moment.

It seems more natural to pass multiple instances of JointLikelihoods each containing different fits. 

@giacomov , can you provide some insight?

**Comment by giacomov** [comment]
@drJfunk is this still relevant? If so, can you expand on the question?

If this has been solved already, I'll go ahead and close the issue.

**Comment by drJfunk** [comment]
This is a complex one. Perhaps needing a longer discussion.
