### ISSUE TITLE
MCMC calculation in examples folder appears to be obsolete

### ISSUE THREAD

**Issue by sybenzvi** [giacomov/3ML#5]
It looks like the MCMC calculation in the notebook examples/090217206.ipynb uses an obsolete version of the JointLikelihood interface. As a result there is no documentation on the correct way to call the Bayesian calculations in the 3ML library.

**Comment by giacomov** [comment]
Hi Segev,
thanks for noticing!

yes, the examples are outdated. I am working on an updated version to
upload, it will be coming up.

We have made radical changes in the last few months to prepare the support
for extended sources, I have been slow in updating everything to reflect
those changes.

**Comment by sybenzvi** [comment]
Sure, no worries. I was able to piece together a calculation by looking at the bayesianAnalysis interface, which seems pretty self-explanatory.

Unfortunately while the priors on the free parameters seem to work correctly, my PT MCMC always hovers around the values of the free parameters in the likelihood object before the calculation starts rather than exploring the full space. Perhaps I'm supposed to randomly seed the likelihood before starting the MCMC. A good example would be very much appreciated!
