### ISSUE TITLE
LAT Like display

### ISSUE THREAD

**Issue by drJfunk** [giacomov/3ML#64]
I believe the model-data/model residual plot has the label or the execution of the math reversed. They do not line up :)

**Comment by giacomov** [comment]
Could you post a picture? I am not sure I understand what you are referring to, sorry...

**Comment by drJfunk** [comment]
you have the residuals labeled (model -data)/model

but you are plotting data-model/ model

<img width="571" alt="screenshot 2016-09-19 22 51 25" src="https://cloud.githubusercontent.com/assets/6764007/18648602/a8612f22-7ebb-11e6-9e34-e2fa647df63c.png">
