### ISSUE TITLE
Background subtracted data

### ISSUE THREAD

**Issue by grburgess** [giacomov/3ML#70]
There are some cases where the background is subtracted off (Swift BAT) and normally, the lowest information statistic to assume for the variance is a normal distribution. However, it may be possible to substitute a Skellam distribution in this case. This is the difference between two Poisson variables. It asymptotically approaches a normal distribution, but has a more peaked structure at low "counts." 

It may be worth exploring how well this performs and is easy to implement. Thoughts @giacomov ?

**Comment by giacomov** [comment]
As we discussed already in another channel, Swift BAT spectra are not the results of the subtraction of two Poisson distribution, so the Skellam distribution is not appropriate.

They should use Chisquare instead, which however is not implemented yet as statistic.

**Comment by drJfunk** [comment]
Agreed. Now that I knows that this is the case. You want me have a look at adding this in?

**Comment by giacomov** [comment]
sure!
