### ISSUE TITLE
Mac OS 10.10 installation and compilation with anaconda

### ISSUE THREAD

**Issue by omodei** [giacomov/3ML#97]
I have success to install everything on my mac using anaconda. After installing root (6.04), I had to change the _iminuit_ requirement to 1.1 (1.2 seems to not be available for mac on anaconda).

**Comment by giacomov** [comment]
thanks for the info!

Regarding iminuit, if you can, what does happen if you try to install it separately using pip:

> pip install iminuit==1.2

What does pip say?

**Comment by grburgess** [comment]
@omodei I guess you have tried the new conda install? Are there any issues remaining?
